### ISSUE TITLE
Error in installation from Bioconductor

### ISSUE THREAD

**Issue by agnesblch** [sneumann/Rdisop#27]
Hi,
An error occurred when I tried to install Rdisop from Bioconductor using `BiocManager::install("Rdisop")`. Here is the message displayed in the R console:

> disop.cpp: In instantiation of ‘SEXPREC* rlistScores(std::multimap<score_type, ims::ComposedElement, std::greater<score_type> >, int) [with score_type = double; SEXP = SEXPREC*]’:
> disop.cpp:352:20:   required from here
> disop.cpp:685:19: error: format not a string literal and no format arguments [-Werror=format-security]
>   685 |           Rf_error(exceptionMesg);
>       |           ~~~~~~~~^~~~~~~~~~~~~~~
> cc1plus: some warnings being treated as errors
> make: *** [/usr/lib/R/etc/Makeconf:204: disop.o] Error 1
> ERROR: compilation failed for package ‘Rdisop’
> * removing ‘/home/abarnabe/R/x86_64-pc-linux-gnu-library/4.4/Rdisop’
> 
> The downloaded source packages are in
> 	‘/tmp/Rtmp5QgOZr/downloaded_packages’
> Warning message:
> In install.packages(...) :
>   installation of package ‘Rdisop’ had non-zero exit status

I can see on your GitHub repo that the commit 8805731 solved this issue. So I downloaded the source package from Bioconductor and applied the modification in disop.cpp as performed in this commit. The installation succeeds perfectly. 

However, I prefer the installation of packages through Bioconductor to simplify the update. Do you know when this error will be corrected?

Thanks in advance.

**Comment by sneumann** [comment]
Hi 1.65.1 is out on BioC for a while now
https://bioconductor.org/checkResults/devel/bioc-LATEST/Rdisop/
I guess this can be closed now. Yours, Steffen
